// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3GEicCab3Oo2uGUwWZi_a5B-oP9jiMoQ',
    appId: '1:478470398006:web:a194b9c58cc2a99be03897',
    messagingSenderId: '478470398006',
    projectId: 'student-registration-app-61695',
    authDomain: 'student-registration-app-61695.firebaseapp.com',
    storageBucket: 'student-registration-app-61695.firebasestorage.app',
    measurementId: 'G-P4G1RMJTXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsTgmAtbECQySCUAPLPCmRkZOcNsRHTLk',
    appId: '1:478470398006:android:e5b9ce8547cc7cc8e03897',
    messagingSenderId: '478470398006',
    projectId: 'student-registration-app-61695',
    storageBucket: 'student-registration-app-61695.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQFQjYCrKFgggzsPzd88mtprPDGvY13U',
    appId: '1:478470398006:ios:3a9a82a3dd6db5dbe03897',
    messagingSenderId: '478470398006',
    projectId: 'student-registration-app-61695',
    storageBucket: 'student-registration-app-61695.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMQFQjYCrKFgggzsPzd88mtprPDGvY13U',
    appId: '1:478470398006:ios:3a9a82a3dd6db5dbe03897',
    messagingSenderId: '478470398006',
    projectId: 'student-registration-app-61695',
    storageBucket: 'student-registration-app-61695.firebasestorage.app',
    iosBundleId: 'com.example.studentRegistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3GEicCab3Oo2uGUwWZi_a5B-oP9jiMoQ',
    appId: '1:478470398006:web:0e951910564c3aede03897',
    messagingSenderId: '478470398006',
    projectId: 'student-registration-app-61695',
    authDomain: 'student-registration-app-61695.firebaseapp.com',
    storageBucket: 'student-registration-app-61695.firebasestorage.app',
    measurementId: 'G-VN1PPZC764',
  );
}
